// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void When_a_new_user_joins() {
    // Test name: When a new user joins
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/default.htm |  | 
    driver.Navigate().GoToUrl("http://localhost:8080/default.htm");
    // 2 | click | css=body |  | Click the date
    driver.FindElement(By.CssSelector("body")).Click();
    // 3 | click | css=body |  | Click the time
    driver.FindElement(By.CssSelector("body")).Click();
    // 4 | click | css=tr:nth-child(3) > td:nth-child(2) |  | Message Time
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2)")).Click();
    // 5 | click | css=tr:nth-child(3) > td:nth-child(3) |  | Message User
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(3)")).Click();
    // 6 | click | css=tr:nth-child(3) > td:nth-child(4) |  | Message Text
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(4)")).Click();
  }
}
